import Head from 'next/head'
import React, {useState, useEffect} from 'react'
import Row from './row';
import styles from '../styles/Home.module.css'
import wordlStyles from '../styles/Wordl.module.css'

import { checkGuess, gotWord, pickRandomAnswer } from './util/check-guess';
const answerArr = ['pants', 'grind', 'hotel', 'fiend', 'ought', 'clamp', 'tried', 'trial', 'farse', 'reads', 'stone', 'cried']
const answer = pickRandomAnswer({answerArr})

export default function Home() {
  const [guess, setGuess] = useState('');
  const [didWin, setWinState] = useState(false);

  const guessArr = checkGuess({guess, answer})

  useEffect(() => {
    console.log('useeffect: ', guessArr);
    if (gotWord({guessArr})) {
      console.log('gotWord: ', gotWord({guessArr}));
      setWinState(true)
    }
  }, [guess])
  return (
    <div className={`${styles.container} ${didWin ? wordlStyles.winner : null}`}>
      <Head>
        <title>world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          wordl
        </h1>

        <div className="flex flex-column">
          <Row guess={guessArr}/>
          {/* <Row /> */}
          {/* <Row /> */}
          {/* <Row /> */}
          {/* <Row /> */}
          <input name="guess" id="guess" type="text" placeholder='guess' maxLength="5"
          onChange={(e) => {
            let guess = e.target.value;
            if (guess.length === 5) {
              setGuess(guess.toUpperCase())
            }
          }} />

        </div>

      </main>

      <footer className={styles.footer}>
<p>Made with ❤️ by alyssa</p>
      </footer>
    </div>
  )
};
