import Head from 'next/head'
import React, {useState} from 'react'
import Row from './row';
import styles from '../styles/Home.module.css'

const answerString = 'freak'
const answer = answerString.split('');

export default function Home() {
  const [guess, setGuess] = useState('');
  const guessArr = []
  guess.split("").forEach((gLetter, gi) => {
    const gObj = { letter: gLetter, color: 'white' };
    if (answer.includes(gLetter)) {
      gObj.color = 'yellow';
    }
    answer.forEach((aLetter, ai) => {
      if (aLetter === gLetter && ai === gi) {
        gObj.color = 'green';
        return;
      }
      return;
    });
    guessArr.push(gObj)
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          wordl
        </h1>

        <div className="flex flex-column">
          <Row guess={guessArr}/>
          {/* <Row />
          <Row />
          <Row />
          <Row /> */}
          <input name="guess" id="guess" type="text" placeholder='guess' onChange={(e) => {
            let guess = e.target.value;
            if (guess.length === 5) {
              setGuess(guess)
            }
          }} />

        </div>

      </main>

      <footer className={styles.footer}>
<p>Made with ❤️ by alyssa</p>
      </footer>
    </div>
  )
};
