import Head from 'next/head'
import Image from 'next/image'
import React, {useState} from 'react'
import Row from './row';
import styles from '../styles/Home.module.css'
// import wordlStyles from '../styles/Wordl.module.css'
const answerString = 'brunt'
const answer = answerString.split('');

export default function Home() {
  const [guess, setGuess] = useState('');
  const guessArr = []
  guess.split("").forEach((gLetter, gi) => {
    const gObj = {letter: gLetter, color: 'white'}
    if (answer.includes(gLetter)) {
      // console.log('GUESS INCLUDES LETTER: ', );
      gObj?.color = 'yellow';
    }
    answer.forEach((aLetter, ai) => {
      if (aLetter === gLetter && ai === gi) {
        console.log('LETTERS SAME: ', aLetter, gLetter);
        // console.log(aLetter, ' ', gObj);
        gObj?.color = 'green';
        return;
      }
      return;
    });
    guessArr.push(gObj)
  });

  // guessArr.forEach((gObj) => {
  //   answer.forEach((aLetter) => {
  //     if (aLetter === gObj.letter) {
  //       // console.log('LETTERS SAME: ', );
  //       return gObj?.color = 'green';
  //     }
  //     console.log('', answer, ' ', gObj);
  //   });
  //   if (answer.includes(gObj.letter)) {
  //     // console.log('GUESS INCLUDES LETTER: ', );
  //     return gObj?.color = 'yellow';
  //   }
// });

  return (
    <div className={styles.container}>
      <Head>
        <title>world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          wordl
        </h1>

        <div className="flex flex-column">
          <Row guess={guessArr}/>
          {/* <Row />
          <Row />
          <Row />
          <Row /> */}
          <input name="guess" id="guess" type="text" placeholder='guess' onChange={(e) => {
            let guess = e.target.value;
            if (guess.length === 5) {
              setGuess(guess)
            }
          }} />

        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
};
